spring:
  application:
    name: Dummy-VideoClub-GraphQL-Server

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: false
  playground:
    enabled: true
    tabs:
      - name: Complex query
        query: classpath:exampleQueries/example1.graphql
      - name: Insert query
        query: classpath:exampleQueries/example2.graphql