spring:
  application:
    name: Dummy-VideoClub-GraphQL-Server

server:
  http2:
    enabled: true

graphql:
  servlet:
    maxQueryDepth: 100
    exception-handlers-enabled: false
  playground:
    enabled: true
    tabs:
      - name: Complex query
        query: classpath:exampleQueries/example1.graphql
      - name: Insert mutation
        query: classpath:exampleQueries/example2.graphql
      - name: Change mutation
        query: classpath:exampleQueries/example3.graphql
      - name: Debug # TODO: REMOVE
        query: classpath:exampleQueries/debug.graphql
  voyager:
    enabled: true